apiVersion: v1
description: Fantastyczna aplikacja UW
home: https://www.ibm.com
icon: https://www.uw.edu.pl/wp-content/uploads/2017/07/logo-2-11.png
keywords:
- fantastic
- ppc64le
- OpenSource
maintainers:
- name: Michal
name: uwapp
sources:
- https://github.com/michalteofan/charts/tree/master/sources
tillerVersion: '>=2.7.2'
version: 0.3.0
